name: Metrics
on:
  # Schedule updates (every day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: ivan770/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: ivan770
          template: classic
          base: header, activity, repositories
          config_timezone: Etc/UTC
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 10
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: public
          plugin_calendar: yes
          plugin_calendar_limit: 1
          plugin_lines: yes
          plugin_lines_history_limit: 0
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          repositories_affiliations: ""
          repositories_forks: yes
